APT::FTPArchive::Release::Origin "Zurvan Linux";
APT::FTPArchive::Release::Label "Zurvan Linux";
APT::FTPArchive::Release::Suite "zurvan";
APT::FTPArchive::Release::Codename "zurvan";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Zurvan Linux custom APT repository (signed-by https://repo.zurvanlinux.org/public.key)";
